// packages/app-react-intro/src/components/benchmark-nav.tsx
import React from 'react';

type BenchmarkNavProps = {
  active?: string,
};

const list = [{
  link: '/vanilla',
  name: 'Vanilla JS',
}, {
  link: '/benchmark?functional=true',
  name: 'Vue3 FC',
}, {
  link: '/benchmark',
  name: 'Vue3',
}, {
  link: '/react/benchmark',
  name: 'React',
}];

export default function BenchmarkNav({ active }: BenchmarkNavProps) {
  return (
    <nav className="benchmark-nav">
      Benchmark Tests:
      <span className="benchmark-list">
        {
          list.map((item, idx) => (
            <React.Fragment key={item.name}>
              { item.name === active
                ? <span>{item.name}</span>
                : <>
                    <a
                      href={item.link}
                      target="_blank"
                      rel="noreferrer"
                    >
                      { item.name }
                    </a>
                  </>
              }
              { idx === list.length - 1 ? undefined : '|'}
            </React.Fragment>
          ))
        }
      </span>
    </nav>
  );
}

// playground/app-vue3-intro/src/components/benchmark-nav.vue
<template>
  <nav className="benchmark-nav">
    All Benchmarks:
    <span class="benchmark-list">
      <template
        v-for="(item, idx) in list"
        :key="item.name"
      >
        <span v-if="item.name === active">{{ item.name }}</span>
        <template v-else>
          <a
            :href="item.link"
            target="_blank"
            rel="noreferrer"
          >
            {{ item.name }}
          </a>
        </template>{{ idx === list.length - 1 ? undefined : '|' }}
      </template>
    </span>
  </nav>
</template>

<script setup lang="ts">
type BenchmarkNavProps = {
  active?: string,
};

defineProps<BenchmarkNavProps>();

const list = [{
  link: '/vanilla',
  name: 'Vanilla JS',
}, {
  link: '/benchmark?functional=true',
  name: 'Vue3 FC',
}, {
  link: '/benchmark',
  name: 'Vue3',
}, {
  link: '/react/benchmark',
  name: 'React',
}];
</script>
<style lang="scss">
.benchmark-nav {
  margin-top: 1rem;
  margin-bottom: 1rem;
  .benchmark-list {
    a, span {
      padding: 0 10px;
      text-align: center;
    }
  }
}
</style>
