// packages/app-react-intro/src/pages/index.tsx
import { useState } from 'react';
import '@/styles/pages/index.scss';
import { useAppDispatch, useAppSelector } from '@/hooks/store';
import {
  selectCount,
  selectLuckyNumber,
  increaseCount,
  setLuckyNumber,
} from '@/store/slices/vise-intro';
import { fetchLuckyNumber } from '@/services';
import BenchmarkNav from '@/components/benchmark-nav';

function PageIndex() {
  const dispatch = useAppDispatch();

  const [localCount, setCount] = useState(0);

  const luckyNumber = useAppSelector(selectLuckyNumber);
  const [luckyNumberToDisplay, setLuckyNumberToDisplay] = useState(String(luckyNumber));
  const updateLuckyNumber = () => {
    setLuckyNumberToDisplay('--');
    setTimeout(() => {
      // 额外包装一层是为了规避 @typescript-eslint/no-misused-promises 报错
      (async () => {
        const num = await fetchLuckyNumber();
        dispatch(setLuckyNumber(num));
        setLuckyNumberToDisplay(String(num));
      })();
    }, 100);
  };

  const countInStore = useAppSelector(selectCount);
  const title = 'Vise: SSR with Vite + TypeScript + Server Hooks';

  return (
    <div className="theme-default-content">
      <div className="top-title">
        <h1>React Version</h1>
        <h1>{ title }</h1>
        <p>
          <img
            className="main-logo"
            src="./logo.svg"
            alt="logo"
          />
        </p>
        <div className="lucky-num">
          Lucky Number from API: { luckyNumberToDisplay }
        </div>
        <button onClick={() => setCount(localCount => localCount + 1)}>
          local count is: { localCount }
        </button>&nbsp;
        <button onClick={() => dispatch(increaseCount())}>
          store count is: { countInStore }
        </button>&nbsp;
        <button onClick={() => updateLuckyNumber()}>
          fetch again
        </button>
      </div>
      <div style={{ textAlign: 'center', fontSize: '22px', margin: '20px' }}>
        This page is rendered with vise react. More documents coming soon...
      </div>
      <BenchmarkNav/>
    </div>
  );
}

export default PageIndex;

// packages/app-vue3-intro/src/pages/index.vue
<template>
  <div class="theme-default-content">
    <div class="top-title">
      <h1>{{ title }}</h1>
      <p>
        <img
          class="main-logo"
          src="/logo.svg"
          alt="logo"
        >
      </p>
      <div class="lucky-num">
        Lucky Number from API: {{ luckyNumber }}
      </div>
      <button @click="state.count++">
        local count is: {{ state.count }}
      </button>&nbsp;
      <button @click="increaseCount()">
        store count is: {{ count }}
      </button>&nbsp;
      <button @click="fetchLuckyNum()">
        fetch again
      </button>
      <filled-markdown-viewer />
    </div>
    <BenchmarkNav />
  </div>
</template>
<script lang="ts">
import { reactive, computed, defineComponent, onMounted, ref } from 'vue';
import useMarkdown from '@/composable/use-markdown';
import useCount from '@/composable/use-count';
import useTitle from '@/composable/use-title';
import mdContent from '@/data/markdown/index.md?raw';
import { useStore, MutationTypes } from '@/store/';
import { fetchLuckyNumber } from '@/services';
import BenchmarkNav from '@/components/benchmark-nav.vue';

const { FilledMarkdownViewer } = useMarkdown('introduction', mdContent);

export default defineComponent({
  components: {
    FilledMarkdownViewer,
    BenchmarkNav,
  },
  setup() {
    const { setTitle } = useTitle();
    const title = 'Vise: SSR with Vite + TypeScript + Server Hooks';
    setTitle(title);

    const store = useStore();
    const { count, increaseCount } = useCount();

    const luckyNumber = computed(() => (loadingLuckyNumber.value ? '--' : store.state.luckyNumber));
    const loadingLuckyNumber = ref(false);
    const fetchLuckyNum = () => {
      loadingLuckyNumber.value = true;
      setTimeout((() => async () => {
        const newLuckyNumber = await fetchLuckyNumber();
        store.commit(MutationTypes.UPDATE_LUCKY_NUM, { newLuckyNumber });
        loadingLuckyNumber.value = false;
      })(), 100);
    };
    onMounted(() => {
      if (luckyNumber.value === -1) {
        fetchLuckyNum();
      }
    });

    const state = reactive({
      count: 0,
    });

    return {
      title,

      count,
      increaseCount,

      luckyNumber,
      fetchLuckyNum,

      state,
    };
  },
});
</script>

<style lang="scss">
.top-title {
  text-align: center;
}
.lucky-num {
  margin: 10px;
}
.main-logo {
  width: 30vw;
}
</style>
