// packages/vue3/template/base/src/app.vue
<template>
  <router-view v-slot="{ Component, route }">
    <main class="page">
      <component
        :is="Component"
        :key="route.path"
      />
      <footer>
        Proudly served with Vise express server.
      </footer>
    </main>
  </router-view>
</template>
<script lang="ts" setup>
</script>
<style lang="scss">
@import './styles/index'
</style>

// packages/react/template/base/src/app.tsx
import './styles/index.scss';

function App({ RouterView }: { RouterView: () => JSX.Element }) {
  return (
    <div className="theme-container">
      <main className="page">
        <RouterView />
        <footer>
          Proudly served with Vise express server.
        </footer>
      </main>
    </div>
  );
}

export default App;
